export const ERROR_CODES = {
  BAD_REQUEST: "REQUEST_400",
  VALIDATION: "VALIDATION_001",
  UNAUTHORIZED: "AUTH_401",
  NOT_FOUND: "RESOURCE_404",
  FORBIDDEN: "AUTH_403",
  CONFLICT: "RESOURCE_409",
  RATE_LIMIT: "RATE_LIMIT_429",
  SERVICE_UNAVAILABLE: "SERVICE_503",
  INTERNAL: "INTERNAL_500",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
